### PR TITLE
Adding System1M module

### PR DESCRIPTION
**Pull request by pstoica**
I've been using the System1M code from https://github.com/kindohm/tidal-midi-rack and just ported it over to the new tidal-midi format.

I decided not to use the normal tidal parameters since so much else is specific to the device. Happy to reconsider.

Let me know if I messed anything up!

### CODE REVIEW

**Comment by lennart** [comment]
Thanks for this pull request, happy to see someone adapting the latest way to write MIDI mappings.

I understand your decision to _not_ use the normal tidal parameters and I see myself struggling with porting the DSI Tetra bindings to 0.8 (it's a lot).

However I think it would be good to use the normal params for at least the unambigous cases like that Dirt/SuperDirt and MIDI synthesizers share:

- lowpass filter cutoff frequency: `cutoff`
- lowpass filter resonance: `resonance`
- highpass filter cutoff frequency: `hcutoff`
- highpass filter cutoff frequency: `hresonance`

if you want to use a consistent naming scheme when using this mapping, you can always _alias_ the functions as you like, e.g.: `rlpcutoff = cutoff`. (Caveat: you would also have to alias `rlpcutoff_p = cutoff_p` to use it in functions like `grp`, e.g. `grp [rlpcutoff_p,rres_p] "0.7:0.3 0.3:0.8"`)

The advantadge I would see with this practice is simply less mental overhead for common parameters, that is instead of trying to figure out alternative names for _low pass filter cutoff_ you can always use `cutoff` regardless of whether you are currently talking to a __System1M__ or a software sampler.

I am tending to merge this pull request anyhow, so that anyone with a `System1M` can profit from your mapping. Though I might ask you to update it once we settle on some kind of convention for naming/reusing parameters.

A side note here regarding defaults: I see all of your parameters you define have a default of `0`, is this intentional?

When moving over to mostly reusing parameters from Tidal, defaults are important since e.g. `cutoff` has a default of `0` and this might lead to do `m1 $ n "a"` and you hear nothing since the filter might cutoff _everything_ by default. For the Tetra I chose to recreate the param definitions with different defaults and use them in the `ControllerShape` while using the standard function when creating patterns:

```haskell
myShape = ControllerShape {
controls = [
mCC cutoff_p' 33
],
latency = 0.1
}

(_, cutoff_p') = pF "cutoff" (Just 1)
```

Ok this should already be enough for now, will leave this PR open until tomorrow I guess, just in case.

kindly,

lennart

**Comment by pstoica** [comment]
Thanks for the feedback! Reusing those params makes sense, especially since I can alias if needed. I'll make those changes and let you know when they're up.

I'll add better defaults too. In my testing, however, it didn't seem like unspecified params were being sent over with default values or anything, else like you mentioned I wouldn't have heard anything. Is that expected? I manually tweak parameters on the synth a lot, so I wouldn't want all my values getting overridden.

**Comment by lennart** [comment]
Regarding the last question, this is something I am currently working on for tidal-midi 0.9, resetting unspecified params to default.

this is currently only done once the stream is initialized with `midiSetters`, however, I would expect it to behave just as tidal does, so params _should_ get reset to default when they removed from a pattern.

As you say, it might however be unexpected if that happens, so I guess I will hide it behind a flag (not sure what the default behavior will be)

**Comment by pstoica** [comment]
Are you actually okay with merging as-is for now? I just ported the Rytm over too and wanted to make a PR for that. Haven't had a chance to map to standard tidal params yet, but I feel the Rytm especially wouldn't benefit from standard params since so much is device-specific and fine tuned (e.g. there's only one filter with a filter type param, instead of lp and hp). The 1M may have a couple sensible ones. Anyway, we can revisit!

**Comment by pstoica** [comment]
Never mind on the Rytm, this one looks simpler: https://github.com/kindohm/tidal-midi-rack/blob/master/Sound/Tidal/Rytm.hs

**Comment by lennart** [comment]
yup, just as you said, we can revisit. I'll merge this as is since we currently have _no_ mapping for **System1M**

**Comment by lennart** [comment]
oops, I merged this into master, but this will not reach people installing tidal-midi via cabal until we release another version. we have some other synths ported that already live in 0.9-dev, but I think adding mappings should not bump a minor version right now. I'll see...

**Comment by kindohm** [comment]
@pstoica yeah the RYTM is kind of its own beast and I have found that it doesn't translate to live coding in Tidal very well. I once had _many_ of its MIDI CC params defined in a custom tidal-midi synth, but it was way too difficult to use. I've found that just defining the eight synth params and the performance CC's are enough for me. Feel free to take it further, if you wish, but I probably won't be expanding the RYTM synth further.

I also don't own the System-1M any more either and don't intent on maintaining that code further. Thanks for porting it!

**Pull request merged**
