### PR TITLE
MIDI support for Meeblip Anode Synthesizer

### PR DESCRIPTION
**Pull request by johannesgunnar**
My first ever pull request! Feedback is welcomed!

An implementation of all the MIDI parameters of the Meeblip Anode open source synth (even the hidden ones).

One thing people might want to review is the names of MIDI parameters. I've tried sticking to similar naming schemes to other synth implementations but had to improvise with some names. (oscboct for example).

http://meeblip.com/

### CODE REVIEW

**Comment by lennart** [comment]
sorry this has been lying around for so long.

right now this cannot be merged and since tidal-midi will probably be updated soonish, I am not sure what to do with it.

Above all, you can now reuse params from Tidal, that is `gain` `cutoff` `resonance` and the like are available, ControllerShapes work a bit different now.

Please ask if its unclear how to port your mapping to latest tidal-midi.

**Comment by kindohm** [comment]
Recommend this be closed. It's unfortunate this wasn't merged before the major 0.7 and 0.8 changes, but the code isn't compatible with the current code base.

**Comment by johannesgunnar** [comment]
Agreed, closing this.

**Comment by lennart** [comment]
@johannesgunnar it might be easier if the generic midi stuff and the meeblip anode are separate pull requests. the anode should be easier to port I guess.

**Pull request closed without merging**
